const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Food = require("../models/Food");

dotenv.config({ path: "./.env" });

const foods = [
  // ─── Meat & Poultry ───────────────────────────────────────────────
  {
    name: "Chicken Breast / Murgi ka Seena",
    category: "Meat & Poultry",
    servingSize: 100,
    servingUnit: "g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    maxDailyQuantity: 400,
    maxPerMealQuantity: 200,
  },
  {
    name: "Chicken Thigh / Murgi ki Ran",
    category: "Meat & Poultry",
    servingSize: 100,
    servingUnit: "g",
    calories: 209,
    protein: 26,
    carbs: 0,
    fat: 11,
    maxDailyQuantity: 400,
    maxPerMealQuantity: 200,
  },
  {
    name: "Chicken Curry / Murgi ka Salan",
    category: "Meat & Poultry",
    servingSize: 100,
    servingUnit: "g",
    calories: 190,
    protein: 16,
    carbs: 4,
    fat: 13,
    maxDailyQuantity: 400,
    maxPerMealQuantity: 200,
  },
  {
    name: "Chicken Tikka / Chicken Tikka",
    category: "Meat & Poultry",
    servingSize: 100,
    servingUnit: "g",
    calories: 170,
    protein: 22,
    carbs: 1,
    fat: 8,
    maxDailyQuantity: 400,
    maxPerMealQuantity: 200,
  },
  {
    name: "Beef Mince / Keema",
    category: "Meat & Poultry",
    servingSize: 100,
    servingUnit: "g",
    calories: 254,
    protein: 26,
    carbs: 0,
    fat: 17,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Seekh Kebab / Seekh Kebab",
    category: "Meat & Poultry",
    servingSize: 100,
    servingUnit: "g",
    calories: 210,
    protein: 20,
    carbs: 2,
    fat: 14,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Mutton / Gosht",
    category: "Meat & Poultry",
    servingSize: 100,
    servingUnit: "g",
    calories: 294,
    protein: 25,
    carbs: 0,
    fat: 21,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Nihari / Nihari",
    category: "Meat & Poultry",
    servingSize: 100,
    servingUnit: "g",
    calories: 255,
    protein: 18,
    carbs: 3,
    fat: 20,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Fish / Machli",
    category: "Meat & Poultry",
    servingSize: 100,
    servingUnit: "g",
    calories: 130,
    protein: 20,
    carbs: 0,
    fat: 5,
    maxDailyQuantity: 400,
    maxPerMealQuantity: 200,
  },

  // ─── Eggs & Dairy ─────────────────────────────────────────────────
  {
    name: "Whole Egg / Anda",
    category: "Eggs & Dairy",
    servingSize: 1,
    servingUnit: "piece",
    calories: 78,
    protein: 6,
    carbs: 0.6,
    fat: 5,
    maxDailyQuantity: 6,
    maxPerMealQuantity: 3,
  },
  {
    name: "Egg White / Anda Safedi",
    category: "Eggs & Dairy",
    servingSize: 1,
    servingUnit: "piece",
    calories: 17,
    protein: 3.6,
    carbs: 0.2,
    fat: 0,
    maxDailyQuantity: 10,
    maxPerMealQuantity: 5,
  },
  {
    name: "Milk / Doodh",
    category: "Eggs & Dairy",
    servingSize: 200,
    servingUnit: "mL",
    calories: 122,
    protein: 6.4,
    carbs: 9.4,
    fat: 6.6,
    maxDailyQuantity: 600,
    maxPerMealQuantity: 400,
  },
  {
    name: "Yogurt / Dahi",
    category: "Eggs & Dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Cheddar Cheese / Cheese",
    category: "Eggs & Dairy",
    servingSize: 30,
    servingUnit: "g",
    calories: 120,
    protein: 7,
    carbs: 0.4,
    fat: 10,
    maxDailyQuantity: 90,
    maxPerMealQuantity: 60,
  },

  // ─── Grains & Bread ───────────────────────────────────────────────
  {
    name: "White Rice / Chawal",
    category: "Grains & Bread",
    servingSize: 100,
    servingUnit: "g",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    maxDailyQuantity: 400,
    maxPerMealQuantity: 200,
  },
  {
    name: "Brown Rice / Brown Chawal",
    category: "Grains & Bread",
    servingSize: 100,
    servingUnit: "g",
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    maxDailyQuantity: 400,
    maxPerMealQuantity: 200,
  },
  {
    name: "Chapati / Roti",
    category: "Grains & Bread",
    servingSize: 1,
    servingUnit: "piece",
    calories: 71,
    protein: 2.5,
    carbs: 13,
    fat: 1.5,
    maxDailyQuantity: 8,
    maxPerMealQuantity: 3,
  },
  {
    name: "Whole Wheat Roti / Atta Roti",
    category: "Grains & Bread",
    servingSize: 1,
    servingUnit: "piece",
    calories: 90,
    protein: 3.5,
    carbs: 17,
    fat: 1.5,
    maxDailyQuantity: 8,
    maxPerMealQuantity: 3,
  },
  {
    name: "Plain Paratha / Paratha",
    category: "Grains & Bread",
    servingSize: 1,
    servingUnit: "piece",
    calories: 260,
    protein: 5,
    carbs: 36,
    fat: 11,
    maxDailyQuantity: 4,
    maxPerMealQuantity: 2,
  },
  {
    name: "Aloo Paratha / Aloo Paratha",
    category: "Grains & Bread",
    servingSize: 1,
    servingUnit: "piece",
    calories: 330,
    protein: 6,
    carbs: 42,
    fat: 16,
    maxDailyQuantity: 3,
    maxPerMealQuantity: 2,
  },
  {
    name: "Plain Naan / Naan",
    category: "Grains & Bread",
    servingSize: 1,
    servingUnit: "piece",
    calories: 262,
    protein: 9,
    carbs: 50,
    fat: 3,
    maxDailyQuantity: 4,
    maxPerMealQuantity: 2,
  },
  {
    name: "White Bread / Safed Bread",
    category: "Grains & Bread",
    servingSize: 1,
    servingUnit: "slice",
    calories: 79,
    protein: 2.7,
    carbs: 15,
    fat: 1,
    maxDailyQuantity: 6,
    maxPerMealQuantity: 3,
  },
  {
    name: "Brown Bread / Brown Bread",
    category: "Grains & Bread",
    servingSize: 1,
    servingUnit: "slice",
    calories: 69,
    protein: 3,
    carbs: 12,
    fat: 1,
    maxDailyQuantity: 6,
    maxPerMealQuantity: 3,
  },

  // ─── Dals & Legumes ───────────────────────────────────────────────
  {
    name: "Red Lentils / Daal Masoor",
    category: "Dals & Legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Split Chickpea Lentils / Daal Chana",
    category: "Dals & Legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 164,
    protein: 9,
    carbs: 27,
    fat: 2.6,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Yellow Lentils / Daal Moong",
    category: "Dals & Legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 105,
    protein: 7,
    carbs: 18,
    fat: 0.4,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "White Lentils / Daal Mash",
    category: "Dals & Legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 130,
    protein: 9,
    carbs: 22,
    fat: 0.5,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Chickpeas / Chanay",
    category: "Dals & Legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 164,
    protein: 8.9,
    carbs: 27,
    fat: 2.6,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Kidney Beans / Rajma",
    category: "Dals & Legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 127,
    protein: 8.7,
    carbs: 22,
    fat: 0.5,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Black Eye Peas / Lobia",
    category: "Dals & Legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 116,
    protein: 7.7,
    carbs: 21,
    fat: 0.5,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Haleem / Haleem",
    category: "Dals & Legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 200,
    protein: 14,
    carbs: 15,
    fat: 9,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },

  // ─── Vegetables ───────────────────────────────────────────────────
  {
    name: "Potato / Aloo",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 200,
  },
  {
    name: "Spinach / Palak",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Tomato / Tamatar",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Onion / Pyaz",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
    maxDailyQuantity: 200,
    maxPerMealQuantity: 100,
  },
  {
    name: "Carrot / Gajar",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Cauliflower / Gobhi",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 25,
    protein: 2,
    carbs: 5,
    fat: 0.3,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Eggplant / Baingan",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 25,
    protein: 1,
    carbs: 6,
    fat: 0.2,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Okra / Bhindi",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 33,
    protein: 2,
    carbs: 7,
    fat: 0.2,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Cucumber / Kheera",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    maxDailyQuantity: 400,
    maxPerMealQuantity: 200,
  },
  {
    name: "Fenugreek Leaves / Methi",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 49,
    protein: 4.4,
    carbs: 6,
    fat: 1,
    maxDailyQuantity: 200,
    maxPerMealQuantity: 100,
  },
  {
    name: "Zucchini / Tori",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 17,
    protein: 1.2,
    carbs: 3.1,
    fat: 0.3,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Bitter Gourd / Karela",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 17,
    protein: 1,
    carbs: 3.7,
    fat: 0.2,
    maxDailyQuantity: 200,
    maxPerMealQuantity: 100,
  },
  {
    name: "Peas / Matar",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 81,
    protein: 5.4,
    carbs: 14,
    fat: 0.4,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },

  // ─── Fruits ───────────────────────────────────────────────────────
  {
    name: "Banana / Kela",
    category: "Fruits",
    servingSize: 1,
    servingUnit: "piece",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    maxDailyQuantity: 3,
    maxPerMealQuantity: 2,
  },
  {
    name: "Apple / Seb",
    category: "Fruits",
    servingSize: 1,
    servingUnit: "piece",
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fat: 0.3,
    maxDailyQuantity: 3,
    maxPerMealQuantity: 2,
  },
  {
    name: "Mango / Aam",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Orange / Narangi",
    category: "Fruits",
    servingSize: 1,
    servingUnit: "piece",
    calories: 62,
    protein: 1.2,
    carbs: 15,
    fat: 0.2,
    maxDailyQuantity: 3,
    maxPerMealQuantity: 2,
  },
  {
    name: "Pomegranate / Anaar",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 83,
    protein: 1.7,
    carbs: 19,
    fat: 1.2,
    maxDailyQuantity: 200,
    maxPerMealQuantity: 100,
  },
  {
    name: "Papaya / Papita",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 43,
    protein: 0.5,
    carbs: 11,
    fat: 0.3,
    maxDailyQuantity: 300,
    maxPerMealQuantity: 150,
  },
  {
    name: "Grapes / Angoor",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 69,
    protein: 0.7,
    carbs: 18,
    fat: 0.2,
    maxDailyQuantity: 200,
    maxPerMealQuantity: 100,
  },
  {
    name: "Guava / Amrood",
    category: "Fruits",
    servingSize: 1,
    servingUnit: "piece",
    calories: 37,
    protein: 1.4,
    carbs: 8,
    fat: 0.5,
    maxDailyQuantity: 4,
    maxPerMealQuantity: 2,
  },
  {
    name: "Watermelon / Tarboz",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    maxDailyQuantity: 400,
    maxPerMealQuantity: 200,
  },

  // ─── Oils & Fats ──────────────────────────────────────────────────
  {
    name: "Cooking Oil / Khana Pakane ka Tel",
    category: "Oils & Fats",
    servingSize: 1,
    servingUnit: "tbsp",
    calories: 120,
    protein: 0,
    carbs: 0,
    fat: 14,
    maxDailyQuantity: 3,
    maxPerMealQuantity: 1,
  },
  {
    name: "Desi Ghee / Desi Ghee",
    category: "Oils & Fats",
    servingSize: 1,
    servingUnit: "tbsp",
    calories: 112,
    protein: 0,
    carbs: 0,
    fat: 13,
    maxDailyQuantity: 3,
    maxPerMealQuantity: 1,
  },
  {
    name: "Butter / Makhan",
    category: "Oils & Fats",
    servingSize: 1,
    servingUnit: "tbsp",
    calories: 102,
    protein: 0.1,
    carbs: 0,
    fat: 11.5,
    maxDailyQuantity: 3,
    maxPerMealQuantity: 1,
  },

  // ─── Breakfast & Snacks ───────────────────────────────────────────
  {
    name: "Oats / Oats",
    category: "Breakfast & Snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 389,
    protein: 17,
    carbs: 66,
    fat: 7,
    maxDailyQuantity: 200,
    maxPerMealQuantity: 100,
  },
  {
    name: "Peanut Butter / Moongphali ka Makhan",
    category: "Breakfast & Snacks",
    servingSize: 2,
    servingUnit: "tbsp",
    calories: 188,
    protein: 8,
    carbs: 6,
    fat: 16,
    maxDailyQuantity: 6,
    maxPerMealQuantity: 4,
  },
  {
    name: "Almonds / Badam",
    category: "Breakfast & Snacks",
    servingSize: 30,
    servingUnit: "g",
    calories: 173,
    protein: 6,
    carbs: 6,
    fat: 15,
    maxDailyQuantity: 60,
    maxPerMealQuantity: 30,
  },
  {
    name: "Walnuts / Akhrot",
    category: "Breakfast & Snacks",
    servingSize: 30,
    servingUnit: "g",
    calories: 196,
    protein: 4.6,
    carbs: 4.1,
    fat: 19.6,
    maxDailyQuantity: 60,
    maxPerMealQuantity: 30,
  },
  {
    name: "Samosa / Samosa",
    category: "Breakfast & Snacks",
    servingSize: 1,
    servingUnit: "piece",
    calories: 150,
    protein: 5,
    carbs: 15,
    fat: 9,
    maxDailyQuantity: 4,
    maxPerMealQuantity: 2,
  },
  {
    name: "Pakora / Pakora",
    category: "Breakfast & Snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 250,
    protein: 5,
    carbs: 25,
    fat: 15,
    maxDailyQuantity: 200,
    maxPerMealQuantity: 100,
  },
  {
    name: "Cornflakes / Cornflakes",
    category: "Breakfast & Snacks",
    servingSize: 30,
    servingUnit: "g",
    calories: 113,
    protein: 2.4,
    carbs: 25,
    fat: 0.3,
    maxDailyQuantity: 90,
    maxPerMealQuantity: 60,
  },

  // ─── Drinks & Beverages ───────────────────────────────────────────
  {
    name: "Doodh Patti Chai / Doodh Patti",
    category: "Drinks & Beverages",
    servingSize: 200,
    servingUnit: "mL",
    calories: 95,
    protein: 3.2,
    carbs: 8,
    fat: 5,
    maxDailyQuantity: 600,
    maxPerMealQuantity: 400,
  },
  {
    name: "Black Tea / Kali Chai",
    category: "Drinks & Beverages",
    servingSize: 200,
    servingUnit: "mL",
    calories: 2,
    protein: 0,
    carbs: 0.5,
    fat: 0,
    maxDailyQuantity: 800,
    maxPerMealQuantity: 400,
  },
  {
    name: "Green Tea / Sabz Chai",
    category: "Drinks & Beverages",
    servingSize: 200,
    servingUnit: "mL",
    calories: 2,
    protein: 0,
    carbs: 0.5,
    fat: 0,
    maxDailyQuantity: 800,
    maxPerMealQuantity: 400,
  },
  {
    name: "Kashmiri Tea / Kashmiri Chai",
    category: "Drinks & Beverages",
    servingSize: 200,
    servingUnit: "mL",
    calories: 120,
    protein: 3.5,
    carbs: 10,
    fat: 7,
    maxDailyQuantity: 600,
    maxPerMealQuantity: 400,
  },
  {
    name: "Sweet Lassi / Meethi Lassi",
    category: "Drinks & Beverages",
    servingSize: 250,
    servingUnit: "mL",
    calories: 200,
    protein: 5,
    carbs: 28,
    fat: 7,
    maxDailyQuantity: 500,
    maxPerMealQuantity: 250,
  },
  {
    name: "Salty Lassi / Namkeen Lassi",
    category: "Drinks & Beverages",
    servingSize: 250,
    servingUnit: "mL",
    calories: 100,
    protein: 5,
    carbs: 8,
    fat: 5,
    maxDailyQuantity: 500,
    maxPerMealQuantity: 250,
  },
  {
    name: "Mango Shake / Aam ka Shake",
    category: "Drinks & Beverages",
    servingSize: 250,
    servingUnit: "mL",
    calories: 280,
    protein: 4,
    carbs: 42,
    fat: 9,
    maxDailyQuantity: 500,
    maxPerMealQuantity: 250,
  },
];

const seedFoods = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("MongoDB connected");

  await Food.deleteMany({});
  console.log("Existing foods cleared");

  await Food.insertMany(foods);
  console.log(`${foods.length} foods seeded successfully`);

  await mongoose.disconnect();
  console.log("MongoDB disconnected");
  process.exit(0);
};

seedFoods();
